-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: Test3Size

function draw(ox, oy, w, h)
  draw_text_bold(ox + 10, oy + 10, "Medium Hi", 0xFFFF)
end
