-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: ZZOrphanTest

function draw(ox, oy, w, h)
  fill_rrect(ox + 0, oy + 0, 20, 20, 0, 0xFFFF, 0x0000)
end
