-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: Siaa

function draw(ox, oy, w, h)
  do
    local halfH = h / 2
    for by = 0, h - 1 do
      local t = 0.5 + (by + 0.5 - halfH) / h
      if t < 0 then t = 0 elseif t > 1 then t = 1 end
      fill_rect(ox, oy + by, w, 1, blend_color(0xF65F, 0xFDB5, t))
    end
  end
  draw_ring(ox + 166, oy + 26, 20, 15, 0.65, 0xFFFF, 0x2104, 0x0000)
  draw_text(ox + 16, oy + 23, "Siaa", 0xFFFF)
  draw_text_bold(ox + 12, oy + 6, string.format("%02d:%02d", get_hour(), get_minute()), 0xFFFF)
end
