-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: 333

function draw(ox, oy, w, h)
  local WD = {"Sun","Mon","Tue","Wed","Thu","Fri","Sat"}
  draw_text(ox + 8, oy + 30, string.format("%s %d", WD[get_weekday() + 1], get_day()), 0x8410)
  draw_text_bold(ox + 8, oy + 14, string.format("%02d:%02d", get_hour(), get_minute()), 0xFFFF)
  draw_ring(ox + 170, oy + 26, 20, 15, 0.65, 0x063F, 0x2104, 0xFFFF)
end
