-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: test2

function draw(ox, oy, w, h)
  draw_ring(ox + 26, oy + 26, 20, 15, 0.65, 0x5B8C, 0x2104, 0x0000)
  draw_ring(ox + 164, oy + 26, 20, 15, 0.65, 0x5B8C, 0x2104, 0x0000)
  draw_ring(ox + 94, oy + 25, 20, 15, 0.65, 0x5B8C, 0x2104, 0x0000)
end
