-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: Test

function draw(ox, oy, w, h)
  draw_ring(ox + 169, oy + 26, 20, 15, 0.65, 0x5B8C, 0x2104, 0x0000)
  draw_text_bold(ox + 11, oy + 8, string.format("%02d:%02d", get_hour(), get_minute()), 0xFFFF)
  local WD = {"Sun","Mon","Tue","Wed","Thu","Fri","Sat"}
  draw_text(ox + 7, oy + 29, string.format("%s %d", WD[get_weekday() + 1], get_day()), 0x8410)
end
