-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: Color

function draw(ox, oy, w, h)
  do
    local halfH = h / 2
    for by = 0, h - 1 do
      local t = 0.5 + (by + 0.5 - halfH) / h
      if t < 0 then t = 0 elseif t > 1 then t = 1 end
      fill_rect(ox, oy + by, w, 1, blend_color(0xCF56, 0x56BF, t))
    end
  end
  draw_ring(ox + 28, oy + 26, 20, 15, 0.65, 0xCF9F, 0xFFFF, 0xD6BA)
  draw_ring(ox + 77, oy + 26, 20, 15, 0.65, 0xCF9F, 0xFFFF, 0xD6BA)
  local WD = {"Sun","Mon","Tue","Wed","Thu","Fri","Sat"}
  draw_text(ox + 130, oy + 30, string.format("%s %d", WD[get_weekday() + 1], get_day()), 0xFFFF)
  draw_text(ox + 137 - 1, oy + 6, string.format("%02d:%02d", get_hour(), get_minute()), 0xF538)
  draw_text(ox + 137 + 1, oy + 6, string.format("%02d:%02d", get_hour(), get_minute()), 0xF538)
  draw_text(ox + 137, oy + 6 - 1, string.format("%02d:%02d", get_hour(), get_minute()), 0xF538)
  draw_text(ox + 137, oy + 6 + 1, string.format("%02d:%02d", get_hour(), get_minute()), 0xF538)
  draw_text(ox + 137, oy + 6, string.format("%02d:%02d", get_hour(), get_minute()), 0xFFFF)
end
