-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: Work

function draw(ox, oy, w, h)
  fill_rect(ox, oy, w, h, 0xB6F1)
  for py = 4, h, 8 do
    for px = 4, w, 8 do
      fill_rect(ox + px - 1, oy + py - 1, 2, 2, 0x4BC5)
    end
  end
  draw_text_bold(ox + 8, oy + 14, string.format("%02d:%02d", get_hour(), get_minute()), 0xFFFF)
  draw_ring(ox + 168, oy + 26, 20, 15, 0.65, 0xEF5D, 0x2104, 0x0000)
  draw_text(ox + 50, oy + 1, "Text", 0xFFFF)
  draw_text(ox + 83, oy + 18, "Text", 0xFFFF)
  draw_text(ox + 115, oy + 33, "Text", 0xFFFF)
end
