-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: Golf

function draw(ox, oy, w, h)
  do
    local dx, dy = -0.0872, -0.9962
    local halfW, halfH = w / 2, h / 2
    local projMax = math.abs(halfW * dx) + math.abs(halfH * dy)
    if projMax < 0.001 then projMax = 1 end
    for by = 0, h - 1, 2 do
      local bh = math.min(2, h - by)
      for bx = 0, w - 1, 2 do
        local bw = math.min(2, w - bx)
        local proj = (bx + bw / 2 - halfW) * dx + (by + bh / 2 - halfH) * dy
        local t = 0.5 + proj / (2 * projMax)
        if t < 0 then t = 0 elseif t > 1 then t = 1 end
        fill_rect(ox + bx, oy + by, bw, bh, blend_color(0x75C8, 0xCF56, t))
      end
    end
  end
  fill_rrect(ox + 161, oy + 14, 24, 24, 60, 0x4BC5, 0x0000)
  fill_rrect(ox + 137, oy + 25, 20, 20, 60, 0x4BC5, 0x0000)
  fill_rrect(ox + 16, oy + 9, 25, 35, 6, 0xFFFB, 0x0000)
  fill_rrect(ox + 44, oy + 9, 25, 35, 6, 0xFFFB, 0x0000)
  fill_rrect(ox + 78, oy + 9, 25, 35, 6, 0xFFFB, 0x0000)
  fill_rrect(ox + 139, oy + 23, 20, 20, 60, 0xFFFF, 0x0000)
  fill_rrect(ox + 106, oy + 9, 25, 35, 6, 0xFFFB, 0x0000)
  draw_text(ox + 24, oy + 17, "1", 0x4AA0)
  draw_text(ox + 52, oy + 18, "0", 0x4AA0)
  draw_text(ox + 86, oy + 17, "2", 0x4AA0)
  draw_text(ox + 113, oy + 18, "6", 0x4AA0)
end
