-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: 3d test

function draw(ox, oy, w, h)
  do
    local halfH = h / 2
    for by = 0, h - 1 do
      local t = 0.5 + (by + 0.5 - halfH) / h
      if t < 0 then t = 0 elseif t > 1 then t = 1 end
      fill_rect(ox, oy + by, w, 1, blend_color(0xF538, 0xFE35, t))
    end
  end
  local ddx1 = math.floor(get_accel_x() * 26 * -0.1)
  local ddy1 = math.floor(get_accel_y() * 26 * -0.1)
  draw_text((ox + 20 + ddx1) + -2, (oy + 16 + ddy1) + -2, "Text", 0x0000)
  draw_text((ox + 20 + ddx1) - 1, (oy + 16 + ddy1), "Text", 0xFFFF)
  draw_text((ox + 20 + ddx1) + 1, (oy + 16 + ddy1), "Text", 0xFFFF)
  draw_text((ox + 20 + ddx1), (oy + 16 + ddy1) - 1, "Text", 0xFFFF)
  draw_text((ox + 20 + ddx1), (oy + 16 + ddy1) + 1, "Text", 0xFFFF)
  draw_text((ox + 20 + ddx1), (oy + 16 + ddy1), "Text", 0xFFFF)
  local ddx2 = math.floor(get_accel_x() * 26 * -0.1)
  local ddy2 = math.floor(get_accel_y() * 26 * -0.1)
  draw_text_bold((ox + 96 + ddx2) + -2, (oy + 16 + ddy2) + -2, string.format("%02d:%02d", get_hour(), get_minute()), 0x0000)
  draw_text_bold((ox + 96 + ddx2) - 1, (oy + 16 + ddy2), string.format("%02d:%02d", get_hour(), get_minute()), 0xFFFF)
  draw_text_bold((ox + 96 + ddx2) + 1, (oy + 16 + ddy2), string.format("%02d:%02d", get_hour(), get_minute()), 0xFFFF)
  draw_text_bold((ox + 96 + ddx2), (oy + 16 + ddy2) - 1, string.format("%02d:%02d", get_hour(), get_minute()), 0xFFFF)
  draw_text_bold((ox + 96 + ddx2), (oy + 16 + ddy2) + 1, string.format("%02d:%02d", get_hour(), get_minute()), 0xFFFF)
  draw_text_bold((ox + 96 + ddx2), (oy + 16 + ddy2), string.format("%02d:%02d", get_hour(), get_minute()), 0xFFFF)
end
