-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: E2E Test Widget

function draw(ox, oy, w, h)
  draw_text(ox + 20, oy + 16, "Text", 0xFFFF)
end
