-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: E2E Test Widget

function draw(ox, oy, w, h)
  draw_text_bold(ox + 8, oy + 14, string.format("%02d:%02d", get_hour(), get_minute()), 0xFFFF)
end
