-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: WW3

function draw(ox, oy, w, h)
  for i = 0, 11 do
    local t = i / 11
    local by = oy + math.floor(h * i / 12)
    local bh = math.ceil(h / 12) + 1
    fill_rect(ox, by, w, bh, blend_color(0xFC70, 0x4916, t))
  end
  fill_rrect(ox + 126, oy + 12, 60, 24, 6, 0xFFFF, 0xFFFF)
  draw_ring(ox + 166, oy + 120, 20, 15, 0.65, 0x5B8C, 0x2104, 0x0000)
  draw_text(ox + 79, oy + 68, "Text", 0xFFFF)
  local WD = {"Sun","Mon","Tue","Wed","Thu","Fri","Sat"}
  draw_text(ox + 6, oy + 125, string.format("%s %d", WD[get_weekday() + 1], get_day()), 0x8410)
  draw_text_bold(ox + 7, oy + 7, string.format("%02d:%02d", get_hour(), get_minute()), 0xFFFF)
end
