-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: NewNew3d

function draw(ox, oy, w, h)
  do
    local halfH = h / 2
    for by = 0, h - 1 do
      local t = 0.5 + (by + 0.5 - halfH) / h
      if t < 0 then t = 0 elseif t > 1 then t = 1 end
      fill_rect(ox, oy + by, w, 1, blend_color(0xFED5, 0xFDB5, t))
    end
  end
  local ddx1, ddy1 = 0, 0
  if get_accel_x and get_gyro_x and millis then
    local t1 = millis() / 1000.0
    ddx1 = math.floor((get_accel_x() * 20 + get_gyro_x() * 46 + math.sin(t1 * 1.3 + 6.032) * 1.6) * -0.1)
    ddy1 = math.floor((get_accel_y() * 20 + get_gyro_y() * 46 + math.sin(t1 * 0.9 + 6.032 + 1.571) * 1.6) * -0.1)
  end
  draw_text((ox + 84 + ddx1) + -2, (oy + 16 + ddy1) + -7, "Text", blend_color(0x0000, 0x0000, 0.09))
  draw_text((ox + 84 + ddx1) + -1, (oy + 16 + ddy1) + -4, "Text", blend_color(0x0000, 0x0000, 0.17))
  draw_text((ox + 84 + ddx1) + 0, (oy + 16 + ddy1) + -2, "Text", blend_color(0x0000, 0x0000, 0.32))
  draw_text((ox + 84 + ddx1), (oy + 16 + ddy1), "Text", 0xFFFF)
  local ddx2, ddy2 = 0, 0
  if get_accel_x and get_gyro_x and millis then
    local t2 = millis() / 1000.0
    ddx2 = math.floor((get_accel_x() * 20 + get_gyro_x() * 46 + math.sin(t2 * 1.3 + 2.513) * 1.6) * -0.1)
    ddy2 = math.floor((get_accel_y() * 20 + get_gyro_y() * 46 + math.sin(t2 * 0.9 + 2.513 + 1.571) * 1.6) * -0.1)
  end
  draw_ring((ox + 168 + ddx2) + -2, (oy + 28 + ddy2) + -7, 20, 15, 1, blend_color(0x0000, 0x0000, 0.09), blend_color(0x0000, 0x0000, 0.09), 0x0000)
  draw_ring((ox + 168 + ddx2) + -1, (oy + 28 + ddy2) + -4, 20, 15, 1, blend_color(0x0000, 0x0000, 0.17), blend_color(0x0000, 0x0000, 0.17), 0x0000)
  draw_ring((ox + 168 + ddx2) + 0, (oy + 28 + ddy2) + -2, 20, 15, 1, blend_color(0x0000, 0x0000, 0.32), blend_color(0x0000, 0x0000, 0.32), 0x0000)
  draw_ring((ox + 168 + ddx2), (oy + 28 + ddy2), 20, 15, 0.65, 0xFFFF, 0x2104, 0x0000)
  local ddx3, ddy3 = 0, 0
  if get_accel_x and get_gyro_x and millis then
    local t3 = millis() / 1000.0
    ddx3 = math.floor((get_accel_x() * 20 + get_gyro_x() * 46 + math.sin(t3 * 1.3 + 1.257) * 1.6) * -0.4)
    ddy3 = math.floor((get_accel_y() * 20 + get_gyro_y() * 46 + math.sin(t3 * 0.9 + 1.257 + 1.571) * 1.6) * -0.4)
  end
  fill_rrect((ox + 16 + ddx3) + -2, (oy + 16 + ddy3) + -9, 60, 24, 6, blend_color(0x0000, 0x56BF, 0.10), 0x56BF)
  fill_rrect((ox + 16 + ddx3) + -1, (oy + 16 + ddy3) + -6, 60, 24, 6, blend_color(0x0000, 0x56BF, 0.22), 0x56BF)
  fill_rrect((ox + 16 + ddx3) + -1, (oy + 16 + ddy3) + -4, 60, 24, 6, blend_color(0x0000, 0x56BF, 0.39), 0x56BF)
  fill_rrect((ox + 16 + ddx3), (oy + 16 + ddy3), 60, 24, 6, 0x3C5F, 0x56BF)
  fill_rect((ox + 16 + ddx3), (oy + 16 + ddy3) + 24 - 2, 60, 2, blend_color(0xFFFF, 0x3C5F, 0.33))
end
