-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: test

function draw(ox, oy, w, h)
  draw_ring(ox + 26, oy + 26, 20, 15, 0.65, 0x5B8C, 0x2104, 0x0000)
  fill_rrect(ox + 70, oy + 13, 60, 24, 6, 0x063F, 0x0000)
  draw_text(ox + 148, oy + 16, "Text", 0xFFFF)
end
