-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: Test333

function draw(ox, oy, w, h)
  do
    local halfH = h / 2
    for by = 0, h - 1 do
      local t = 0.5 + (by + 0.5 - halfH) / h
      if t < 0 then t = 0 elseif t > 1 then t = 1 end
      fill_rect(ox, oy + by, w, 1, blend_color(0xFE35, 0x3C5F, t))
    end
  end
  local WD = {"Sun","Mon","Tue","Wed","Thu","Fri","Sat"}
  draw_text(ox + 16, oy + 28, string.format("%s %d", WD[get_weekday() + 1], get_day()), 0xFFFF)
  draw_text_bold(ox + 16, oy + 12, string.format("%02d:%02d", get_hour(), get_minute()), 0xFFFF)
  draw_ring(ox + 168, oy + 28, 20, 15, 0.65, 0xEF5D, 0xFECE, 0x0000)
  -- custom code element (ox=ox + 0, oy=oy + 0)
  -- e.g. draw_text(ox + 4, oy + 4, "hi", 0xFFFF)
  -- ox/oy are already in scope here as this element's x/y.
end
