-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: pls

function draw(ox, oy, w, h)
  draw_text(ox + 20, oy + 16, "Text", 0xFFFF)
  local WD = {"Sun","Mon","Tue","Wed","Thu","Fri","Sat"}
  draw_text(ox + 8, oy + 30, string.format("%s %d", WD[get_weekday() + 1], get_day()), 0x8410)
  fill_rrect(ox + 115, oy + 13, 60, 24, 6, 0x2104, 0x0000)
end
