-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: netTest3d

function draw(ox, oy, w, h)
  do
    local halfH = h / 2
    for by = 0, h - 1 do
      local t = 0.5 + (by + 0.5 - halfH) / h
      if t < 0 then t = 0 elseif t > 1 then t = 1 end
      fill_rect(ox, oy + by, w, 1, blend_color(0xEF5D, 0xEF5D, t))
    end
  end
  local ddx1, ddy1 = 0, 0
  if get_accel_x and get_gyro_x and millis then
    local t1 = millis() / 1000.0
    ddx1 = math.floor((get_accel_x() * 20 + get_gyro_x() * 46 + math.sin(t1 * 1.3 + 4.272) * 1.6) * 0.1)
    ddy1 = math.floor((get_accel_y() * 20 + get_gyro_y() * 46 + math.sin(t1 * 0.9 + 4.272 + 1.571) * 1.6) * 0.1)
  end
  draw_text((ox + 80 + ddx1) + 2, (oy + 16 + ddy1) + 7, "Text", blend_color(0x0000, 0x0000, 0.09))
  draw_text((ox + 80 + ddx1) + 1, (oy + 16 + ddy1) + 4, "Text", blend_color(0x0000, 0x0000, 0.17))
  draw_text((ox + 80 + ddx1) + 0, (oy + 16 + ddy1) + 2, "Text", blend_color(0x0000, 0x0000, 0.32))
  draw_text((ox + 80 + ddx1), (oy + 16 + ddy1), "Text", 0xFFFF)
  local ddx2, ddy2 = 0, 0
  if get_accel_x and get_gyro_x and millis then
    local t2 = millis() / 1000.0
    ddx2 = math.floor((get_accel_x() * 20 + get_gyro_x() * 46 + math.sin(t2 * 1.3 + 0.251) * 1.6) * 0.3)
    ddy2 = math.floor((get_accel_y() * 20 + get_gyro_y() * 46 + math.sin(t2 * 0.9 + 0.251 + 1.571) * 1.6) * 0.3)
  end
  local WD = {"Sun","Mon","Tue","Wed","Thu","Fri","Sat"}
  draw_text((ox + 128 + ddx2) + 2, (oy + 16 + ddy2) + 8, string.format("%s %d", WD[get_weekday() + 1], get_day()), blend_color(0x0000, 0x0000, 0.10))
  draw_text((ox + 128 + ddx2) + 1, (oy + 16 + ddy2) + 5, string.format("%s %d", WD[get_weekday() + 1], get_day()), blend_color(0x0000, 0x0000, 0.20))
  draw_text((ox + 128 + ddx2) + 1, (oy + 16 + ddy2) + 3, string.format("%s %d", WD[get_weekday() + 1], get_day()), blend_color(0x0000, 0x0000, 0.37))
  draw_text((ox + 128 + ddx2), (oy + 16 + ddy2), string.format("%s %d", WD[get_weekday() + 1], get_day()), 0x8410)
  draw_ring(ox + 26, oy + 26, 20, 15, 0.65, 0x971F, 0xD6BA, 0xFFFF)
end
