-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: Test1

function draw(ox, oy, w, h)
  draw_text(ox + 82, oy + 17, "Test", 0xFFFF)
end
