-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: t1

function draw(ox, oy, w, h)
  fill_rrect(ox + 70, oy + 12, 60, 24, 6, 0x051A, 0x063F)
end
