-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: School clock

function draw(ox, oy, w, h)
  fill_rect(ox, oy, w, h, 0xFFFF)
  for py = 4, h, 8 do
    for px = 4, w, 8 do
      fill_rect(ox + px - 1, oy + py - 1, 2, 2, 0x9492)
    end
  end
  draw_ring(ox + 28, oy + 26, 20, 15, 0.65, 0x56BF, 0x2104, 0x0000)
  fill_rrect(ox + 63, oy + 13, 60, 24, 6, 0xF538, 0x0000)
  fill_rrect(ox + 71, oy + 13, 60, 24, 6, 0xFE9C, 0x0000)
  local WD = {"Sun","Mon","Tue","Wed","Thu","Fri","Sat"}
  draw_text(ox + 75, oy + 15, string.format("%s %d", WD[get_weekday() + 1], get_day()), 0xFFFF)
  draw_ring(ox + 168, oy + 26, 20, 15, 0.65, 0x56BF, 0x2104, 0x0000)
end
