-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: Grid

function draw(ox, oy, w, h)
  fill_rect(ox, oy, w, h, 0x0000)
  for py = 4, h, 8 do
    for px = 4, w, 8 do
      fill_rect(ox + px - 1, oy + py - 1, 2, 2, 0x9492)
    end
  end
  draw_ring(ox + 168, oy + 25, 20, 15, 0.65, 0xFFFF, 0x2104, 0x0000)
  draw_text_bold(ox + 12, oy + 16, string.format("%02d:%02d", get_hour(), get_minute()), 0xFFFF)
  local WD = {"Sun","Mon","Tue","Wed","Thu","Fri","Sat"}
  draw_text(ox + 71, oy + 15, string.format("%s %d", WD[get_weekday() + 1], get_day()), 0x8410)
end
