-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: Widget

function draw(ox, oy, w, h)
  fill_rect(ox, oy, w, h, 0xFDB5)
  draw_text(ox + 91, oy + 16, "Texas", 0xFFFB)
  fill_rrect(ox + 13, oy + 14, 60, 24, 6, 0xFD2F, 0xFDA7)
  local WD = {"Sun","Mon","Tue","Wed","Thu","Fri","Sat"}
  draw_text(ox + 17, oy + 17, string.format("%s %d", WD[get_weekday() + 1], get_day()), 0xFFFF)
  draw_ring(ox + 168, oy + 26, 20, 15, 0.65, 0xFF1A, 0x2104, 0x0000)
end
