-- Generated by Sendtra Widget Studio -- do not hand-edit,
-- re-export from the designer instead so the two stay in sync.
-- Widget: mid card test

function draw(ox, oy, w, h)
  local WD = {"Sun","Mon","Tue","Wed","Thu","Fri","Sat"}
  draw_text(ox + 8, oy + 30, string.format("%s %d", WD[get_weekday() + 1], get_day()), 0x8410)
  draw_ring(ox + 168, oy + 24, 20, 15, 0.65, 0x5B8C, 0x2104, 0x0000)
end
